// Code generated by translate-gen. DO NOT EDIT.
// Source: locale/base.toml

package example

// English
const (
	Hello = `Hello World`
	Name  = `My name is %s`
)

// English Map
func BaseMap() map[interface{}]string {
	return map[interface{}]string{
		Hello: Hello,
		Name:  Name,
	}
}
