// Code generated by translate-gen. DO NOT EDIT.
// Source: french.toml

package example

import (
	httpStuff "net/http"
)

// French
func French() map[interface{}]string {
	return map[interface{}]string{
		Hello:                    `Bonjour le monde`,
		Name:                     `Mon nom est %s`,
		httpStuff.StatusNotFound: `Pas trouvé`,
	}
}
